/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.autumncode.options;

import com.beust.jcommander.JCommander;

import java.util.Arrays;
import java.util.Objects;

public class App {
    public static void main(String[] args) {
        Command command = null;
        try {
            if (args.length > 0) {
                switch (args[0]) {
                    case "a": {
                        A cmd = new A();
                        parseOptions(args, cmd);
                        command = cmd;
                    }

                    break;
                    case "b": {
                        B cmd = new B();
                        parseOptions(args, cmd);
                        command = cmd;
                    }
                    break;
                    case "help":
                        break;
                    default:
                        throw new MissingArgumentException();
                }
                Objects.requireNonNull(command).run();
            } else {
                throw new MissingArgumentException();
            }
        } catch (MissingArgumentException e) {
            System.out.println("requires options a, b, or help");
        }
    }

    private static <K> void parseOptions(String[] args, K command) {
        JCommander
                .newBuilder()
                .addObject(command)
                .build()
                .parse(Arrays.copyOfRange(args, 1, args.length));
    }
}
